module.exports = {
  TASK_UPDATED: 'TASK_UPDATED',
  FOCUS_STARTED: 'FOCUS_STARTED',
  FOCUS_ENDED: 'FOCUS_ENDED',
  REMINDER_PUSH: 'REMINDER_PUSH',
  TASK_LEADERBOARD_UPDATED: 'TASK_LEADERBOARD_UPDATED', // ← ADD THIS
  TASK_COMPLETED_BY_PARTICIPANT: 'TASK_COMPLETED_BY_PARTICIPANT', // if you're using this too
 CHALLENGE_PROGRESS: 'CHALLENGE_PROGRESS',
 CHALLENGE_LEADERBOARD_UPDATED: 'CHALLENGE_LEADERBOARD_UPDATED',
};
